# Generated by Django 4.2 on 2023-05-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mail",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
