# Generated by Django 4.2 on 2023-05-02 10:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_mail"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserData",
        ),
    ]
